employe_index:
    path:     /
    defaults: { _controller: "ensiasGRHBundle:employe:index" }
    methods:  GET

employe_show:
    path:     /{id}/show
    defaults: { _controller: "ensiasGRHBundle:employe:show" }
    methods:  GET

employe_new:
    path:     /new
    defaults: { _controller: "ensiasGRHBundle:employe:new" }
    methods:  [GET, POST]

employe_edit:
    path:     /{id}/edit
    defaults: { _controller: "ensiasGRHBundle:employe:edit" }
    methods:  [GET, POST]

employe_delete:
    path:     /{id}/delete
    defaults: { _controller: "ensiasGRHBundle:employe:delete" }
    methods:  DELETE
