<?php

namespace ensias\GRHBundle\Repository;

/**
 * employeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class employeRepository extends \Doctrine\ORM\EntityRepository
{
}
