<?php

namespace VolsBundle\Repository;

/**
 * voyageurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voyageurRepository extends \Doctrine\ORM\EntityRepository
{
}
